//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.HandsFree.Keyboard.UserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.HandsFree.Keyboard.UserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;36&quot;&gt;
        ///  &lt;Row&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;Char Caption=&quot;1&quot; ShowHints=&quot;false&quot; /&gt;
        ///        &lt;Char Caption=&quot;2&quot; ShowHints=&quot;false&quot; /&gt;
        ///        &lt;Char Caption=&quot;3&quot; ShowHints=&quot;false&quot; /&gt;
        ///        &lt;Char Caption=&quot;4&quot; ShowHints=&quot;false&quot; /&gt;
        ///        &lt;Char Caption=&quot;5&quot; ShowHints=&quot;false&quot; /&gt;
        ///        &lt;Char Caption=&quot;6&quot; ShowHints=&quot;false&quot; /&gt;
        ///        &lt;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;Row&gt;
        ///    &lt;Gap KeyWidth=&quot;0.25&quot;/&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;Char Caption=&quot;1&quot; ShiftCaption=&quot;!&quot; ShiftVocal=&quot;Exclamation Mark&quot; /&gt;
        ///        &lt;Char Caption=&quot;2&quot; ShiftCaption=&quot;@&quot; ShiftVocal=&quot;At&quot; /&gt;
        ///        &lt;Char Caption=&quot;3&quot; ShiftCaption=&quot;#&quot; ShiftVocal=&quot;Hash&quot; /&gt;
        ///        &lt;Char Caption=&quot;4&quot; ShiftCaption=&quot;$&quot; ShiftVocal=&quot;Dollar&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyboardLayout {
            get {
                return ResourceManager.GetString("KeyboardLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;Row&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;Char Caption=&quot;q&quot; /&gt;
        ///        &lt;Char Caption=&quot;w&quot; /&gt;
        ///        &lt;Char Caption=&quot;e&quot; /&gt;
        ///        &lt;Char Caption=&quot;r&quot; /&gt;
        ///        &lt;Char Caption=&quot;t&quot; /&gt;
        ///        &lt;Char Caption=&quot;y&quot; /&gt;
        ///        &lt;Char Caption=&quot;u&quot; /&gt;
        ///        &lt;Char Caption=&quot;i&quot; /&gt;
        ///        &lt;Char Caption=&quot;o&quot; /&gt;
        ///        &lt;Char Caption=&quot;p&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyboardLayoutTabTip {
            get {
                return ResourceManager.GetString("KeyboardLayoutTabTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;Row&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;State KeyHeight=&quot;3&quot; KeyWidth=&quot;0.5&quot; Caption=&quot;&amp;lt;&quot; StateName=&quot;Function&quot;/&gt;
        ///        &lt;Gap KeyWidth=&quot;0.5&quot;/&gt;
        ///        &lt;Toggle Caption=&quot;&amp;#xE110;&quot; StateName=&quot;Shift&quot; /&gt;
        ///        &lt;Char Caption=&quot;q&quot; /&gt;
        ///        &lt;Char Caption=&quot;w&quot; /&gt;
        ///        &lt;Char Caption=&quot;e&quot; /&gt;
        ///        &lt;Char Caption=&quot;r&quot; /&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyboardLayoutTobii {
            get {
                return ResourceManager.GetString("KeyboardLayoutTobii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;Row&gt;
        ///    &lt;Char Caption=&quot;esc&quot; Value=&quot;{ESC}&quot; /&gt;
        ///    &lt;Gap KeyWidth=&quot;0.5&quot;/&gt;
        ///    &lt;Char Caption=&quot;?&quot; Value=&quot;{BACKSPACE}&quot; /&gt;
        ///    &lt;Gap KeyWidth=&quot;0.5&quot;/&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;Char Caption=&quot;1&quot; ShiftCaption=&quot;!&quot; ShiftVocal=&quot;Exclamation Mark&quot; /&gt;
        ///        &lt;Char Caption=&quot;2&quot; ShiftCaption=&quot;@&quot; ShiftVocal=&quot;At&quot; /&gt;
        ///        &lt;Char Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KrohnKeyboard {
            get {
                return ResourceManager.GetString("KrohnKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;Row&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;State Caption=&quot;*!?&quot; StateName=&quot;Numeric&quot; FontSize=&quot;24&quot; Vocal=&quot;Special Keys&quot; /&gt;
        ///        &lt;Gap KeyWidth=&quot;0.5&quot;/&gt;
        ///        &lt;Char Caption=&quot;1&quot; ShiftCaption=&quot;!&quot; ShiftVocal=&quot;Exclamation Mark&quot; /&gt;
        ///        &lt;Char Caption=&quot;2&quot; ShiftCaption=&quot;@&quot; ShiftVocal=&quot;At&quot; /&gt;
        ///        &lt;Char Caption=&quot;3&quot; ShiftCaption= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonArturo14 {
            get {
                return ResourceManager.GetString("NonArturo14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;Row&gt;
        ///    &lt;Action Caption=&quot;done&quot; Action=&quot;SpeakCommand&quot;/&gt;
        ///    &lt;Gap KeyWidth=&quot;0.25&quot; /&gt;
        ///    
        ///    &lt;Action Caption=&quot;q w&quot; Action=&quot;SendAmbiguousKeys&quot;/&gt;
        ///    &lt;Action Caption=&quot;e r&quot; Action=&quot;SendAmbiguousKeys&quot;/&gt;
        ///    &lt;Action Caption=&quot;t y&quot; Action=&quot;SendAmbiguousKeys&quot;/&gt;
        ///    &lt;Action Caption=&quot;u i&quot; Action=&quot;SendAmbiguousKeys&quot;/&gt;
        ///    &lt;Action Caption=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Q15 {
            get {
                return ResourceManager.GetString("Q15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;30&quot;&gt;
        ///  
        ///  &lt;Row&gt;
        ///    &lt;Action Caption=&quot;done&quot; Action=&quot;SpeakCommand&quot; KeyWidth=&quot;2&quot;/&gt;
        ///    &lt;Gap KeyWidth=&quot;0.25&quot; /&gt;
        ///    
        ///    &lt;Action Caption=&quot;q w e r t&quot; Action=&quot;SendAmbiguousKeys&quot; KeyWidth=&quot;2&quot;/&gt;
        ///    &lt;Action Caption=&quot;y u i o p&quot; Action=&quot;SendAmbiguousKeys&quot; KeyWidth=&quot;2&quot;/&gt;
        ///    
        ///    &lt;Gap KeyWidth=&quot;0.25&quot; /&gt;
        ///    &lt;Char Caption=&quot;?&quot; Value=&quot;{BACKSPACE}&quot; M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Q6 {
            get {
                return ResourceManager.GetString("Q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;30&quot;&gt;
        ///  
        ///  &lt;Row&gt;
        ///    &lt;Action Caption=&quot;done&quot; Action=&quot;SpeakCommand&quot; KeyWidth=&quot;2&quot;/&gt;
        ///    &lt;Gap KeyWidth=&quot;0.25&quot; /&gt;
        ///    
        ///    &lt;Action Caption=&quot;q w e&quot; Action=&quot;SendAmbiguousKeys&quot; KeyWidth=&quot;2&quot;/&gt;
        ///    &lt;Action Caption=&quot;r t y&quot; Action=&quot;SendAmbiguousKeys&quot; KeyWidth=&quot;2&quot;/&gt;
        ///    &lt;Action Caption=&quot;u i o p&quot; Action=&quot;SendAmbiguousKeys&quot; KeyWidth=&quot;2&quot;/&gt;
        ///    
        ///    &lt;Ga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Q9 {
            get {
                return ResourceManager.GetString("Q9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;Row Height=&quot;1.25&quot;&gt;
        ///    &lt;Gap KeyWidth=&quot;0.5&quot;/&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;Char Caption=&quot;q&quot; /&gt;
        ///        &lt;Char Caption=&quot;w&quot; /&gt;
        ///        &lt;Char Caption=&quot;e&quot; /&gt;
        ///        &lt;Char Caption=&quot;r&quot; /&gt;
        ///        &lt;Char Caption=&quot;t&quot; /&gt;
        ///        &lt;Char Caption=&quot;y&quot; /&gt;
        ///        &lt;Char Caption=&quot;u&quot; /&gt;
        ///        &lt;Char Caption=&quot;i&quot; /&gt;
        ///        &lt;Char Cap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Supersize {
            get {
                return ResourceManager.GetString("Supersize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; FontSize=&quot;40&quot;&gt;
        ///  &lt;!--Row&gt;
        ///    &lt;Gap KeyWidth=&quot;0.25&quot;/&gt;
        ///    &lt;Group&gt;
        ///      &lt;Conditional&gt;
        ///        &lt;Char Caption=&quot;1&quot; ShiftCaption=&quot;!&quot; ShiftVocal=&quot;Exclamation Mark&quot; /&gt;
        ///        &lt;Char Caption=&quot;2&quot; ShiftCaption=&quot;@&quot; ShiftVocal=&quot;At&quot; /&gt;
        ///        &lt;Char Caption=&quot;3&quot; ShiftCaption=&quot;#&quot; ShiftVocal=&quot;Hash&quot; /&gt;
        ///        &lt;Char Caption=&quot;4&quot; ShiftCaption=&quot;$&quot; ShiftVocal=&quot;Dollar&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThreeRowed {
            get {
                return ResourceManager.GetString("ThreeRowed", resourceCulture);
            }
        }
    }
}
